# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"

default_platform :ios

platform :ios do
  before_all do
    ensure_xcode_version(version: "10.1")
  end

  desc "buid the example project"
  lane :build_example do |options|

    type = options[:type]
    types = {
      "ios" => ["VimeoUpload-iOS", "generic/platform=iOS"],
      "iosold" => ["VimeoUpload-iOS-OldUpload", "generic/platform=iOS"],
    }

    # cant use gym: https://github.com/fastlane/fastlane/issues/1816
    xcodebuild(
      workspace: "VimeoUpload.xcworkspace",
      scheme: types[type][0],
      configuration: "Release",
      build: true,
      destination: types[type][1],
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      },
      buildlog_path: ".",
      derived_data_path: "build/"
    )

  end

  desc "run test"
  lane :run_test do |options|
    # Work-around to hanging simulators
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = "1"
    # custom paths for xcpretty-formatter; see Dangerfile
    ENV['XCPRETTY_JSON_FILE_OUTPUT'] = "build/reports/errors-#{options[:scheme]}.json"
    scan(
      workspace: "VimeoUpload.xcworkspace",
      scheme: options[:scheme],
      configuration: "Debug",
      buildlog_path: ".",
      output_directory: "./fastlane/test_output-#{options[:scheme]}",
      derived_data_path: "build/",
      formatter: 'xcpretty-json-formatter',
    )

    pretty_junit(file_pattern: "./fastlane/test_output-#{options[:scheme]}/report.junit")
  end

  desc "test ios"
  lane :ios do |options|
    run_test(scheme: "VimeoUpload-iOS")
  end

  desc "test ios old"
  lane :iosold do |options|
    run_test(scheme: "VimeoUpload-iOS-OldUpload")
  end

  desc "test all"
  lane :test do |options|
    
    ios
    iosold

    if is_ci?
      danger(use_bundle_exec: false)
    end
    
  end

  desc "bumps the project and podspec version"
  lane :version_bump do |options|    

    bump_type = options[:bump_type]
    version_number = options[:version_number]
    if bump_type.nil? && version_number.nil?
      UI.user_error!("version_bump requires you to provide a bump_type [patch|minor|major] or specific version_number. Please try again.") 
    end

    increment_version_number(
      bump_type: bump_type,
      version_number: version_number,
      xcodeproj: "Framework/VimeoUpload/VimeoUpload.xcodeproj"
    )

    version_bump_podspec(
      bump_type: bump_type,
      version_number: version_number
    )
  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
