# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"

default_platform :ios

platform :ios do
  before_all do
    ensure_xcode_version(version: "8.0")
  end

  desc "buid the example project"
  lane :build_example do |options|

    type = options[:type]
    types = {
      "ios" => ["VimeoUpload-iOS", "generic/platform=iOS"],
      "iosold" => ["VimeoUpload-iOS-OldUpload", "generic/platform=iOS"],
    }

    # cant use gym: https://github.com/fastlane/fastlane/issues/1816
    xcodebuild(
      workspace: "VimeoUpload.xcworkspace",
      scheme: types[type][0],
      configuration: "Release",
      build: true,
      destination: types[type][1],
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      },
      buildlog_path: ".",
      derived_data_path: "build/"
    )

  end

  desc "build ios"
  lane :ios do |options|
    build_example(type:"ios")
  end

  desc "build ios old"
  lane :iosold do |options|
    build_example(type:"iosold")
  end

  desc "build all"
  lane :all do |options|
    
    ios
    iosold
    
  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
